//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testingemailverification.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int qid { get; set; }
        public string Department_Name { get; set; }
        public int Semster_No { get; set; }
        public string Subject_Name { get; set; }
        public string chapter1_twomarkque { get; set; }
        public string chapter1_fifteenmarkque { get; set; }
        public string chapter2_twomarkque { get; set; }
        public string chapter2_fifteenmarkque { get; set; }
        public string chapter3_twomarkque { get; set; }
        public string chapter3_fifteenmarkque { get; set; }
    }
}
